version: '3.8'
services:
  app:
    build: .
    command: sleep 100d
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    labels:
      - traefik.http.services.app.loadbalancer.server.port=4000

  traefik:
    image: traefik:v2.3.5
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tools/traefik:/etc/traefik
    restart: always

