version: '3.8'
services:
  app:
    build: .
    command: >
        sh -c '
          make install-tools &&
          sleep 100d
        '
    expose:
      - 3000
    volumes:
      - .:/usr/src/app
    labels:
      - traefik.http.services.app.loadbalancer.server.port=3000

  traefik:
    image: traefik:v2.3.5
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tools/traefik:/etc/traefik
    restart: always

